using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis.CSharp;

namespace BlazeDb.SourceGen;

internal static class BlazeDbSourceEmitter
{
    private const string Writer = "global::BlazeDb.Serialization.BlazeDbBufferWriter";
    private const string Reader = "global::BlazeDb.Serialization.BlazeDbBufferReader";

    private static string Bool(bool value) => value ? "true" : "false";

    /// <summary>
    /// A C# string literal for <paramref name="value"/>. Table names come straight from an
    /// attribute argument and can hold a quote or a backslash; index names are validated as
    /// identifiers, but go through the same helper so there is one rule rather than two.
    /// </summary>
    private static string Literal(string value) => SymbolDisplay.FormatLiteral(value, quote: true);

    private static string Members(params string[] names) =>
        "new string[] { " + string.Join(", ", Array.ConvertAll(names, Literal)) + " }";

    public static string Emit(BlazeDbTableModel model)
    {
        var self = model.Namespace is null
            ? "global::" + model.TypeName
            : "global::" + model.Namespace + "." + model.TypeName;
        var key = model.Key!;
        var keyType = key.ScalarTypeDisplay;
        var indent = model.Namespace is null ? "" : "    ";

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by BlazeDb.SourceGen />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        if (model.Namespace != null)
        {
            sb.AppendLine($"namespace {model.Namespace}");
            sb.AppendLine("{");
        }

        sb.AppendLine($"{indent}partial {model.TypeKeyword} {model.TypeName}");
        sb.AppendLine($"{indent}{{");

        // Descriptor.
        var indexed = model.Props.Where(p => p.HashIndexName != null || p.OrderedIndexName != null).ToList();
        var indexRefs = new List<string>();
        foreach (var prop in indexed)
        {
            if (prop.HashIndexName != null)
            {
                indexRefs.Add("Indexes." + prop.HashIndexName);
            }
            if (prop.OrderedIndexName != null)
            {
                indexRefs.Add("Indexes." + prop.OrderedIndexName);
            }
        }
        foreach (var compound in model.CompoundIndexes)
        {
            indexRefs.Add("Indexes." + compound.Name);
        }
        var indexArg = indexRefs.Count == 0
            ? "null"
            : $"new global::BlazeDb.BlazeDbIndexDefinition<{self}>[] {{ {string.Join(", ", indexRefs)} }}";

        sb.AppendLine($"{indent}    /// <summary>Generated BlazeDb table descriptor for this type.</summary>");
        sb.AppendLine($"{indent}    public static readonly global::BlazeDb.BlazeDbTableDescriptor<{keyType}, {self}> Table = new(");
        sb.AppendLine($"{indent}        {Literal(model.TableName)},");
        sb.AppendLine($"{indent}        static row => row.{key.Name},");
        sb.AppendLine($"{indent}        __BlazeWriteRow,");
        sb.AppendLine($"{indent}        __BlazeReadRow,");
        sb.AppendLine($"{indent}        __BlazeWriteKey,");
        sb.AppendLine($"{indent}        __BlazeReadKey,");
        sb.AppendLine($"{indent}        {indexArg},");
        sb.AppendLine($"{indent}        keyMember: {Literal(key.Name)});");
        sb.AppendLine();

        // Index definitions.
        if (indexRefs.Count > 0)
        {
            sb.AppendLine($"{indent}    /// <summary>Generated secondary index definitions.</summary>");
            sb.AppendLine($"{indent}    public static class Indexes");
            sb.AppendLine($"{indent}    {{");
            foreach (var prop in indexed)
            {
                if (prop.HashIndexName != null)
                {
                    sb.AppendLine($"{indent}        public static readonly global::BlazeDb.BlazeDbHashIndexDefinition<{self}, {prop.TypeDisplay}> {prop.HashIndexName} =");
                    sb.AppendLine($"{indent}            new({Literal(prop.HashIndexName!)}, static row => row.{prop.Name}, null, {Bool(prop.HashIndexUnique)}, {Members(prop.Name)});");
                }
                if (prop.OrderedIndexName != null)
                {
                    sb.AppendLine($"{indent}        public static readonly global::BlazeDb.BlazeDbOrderedIndexDefinition<{self}, {prop.TypeDisplay}> {prop.OrderedIndexName} =");
                    sb.AppendLine($"{indent}            new({Literal(prop.OrderedIndexName!)}, static row => row.{prop.Name}, null, {Bool(prop.OrderedIndexUnique)}, {Members(prop.Name)});");
                }
            }
            foreach (var compound in model.CompoundIndexes)
            {
                var tuple = compound.TupleType;
                var ctor = "(" + string.Join(", ", compound.Props.ConvertAll(p => "row." + p.Name)) + ")";
                var defType = compound.Ordered ? "BlazeDbOrderedIndexDefinition" : "BlazeDbHashIndexDefinition";
                sb.AppendLine($"{indent}        public static readonly global::BlazeDb.{defType}<{self}, {tuple}> {compound.Name} =");
                sb.AppendLine($"{indent}            new({Literal(compound.Name)}, static row => {ctor}, {CompoundComparer(compound)}, {Bool(compound.Unique)}, {Members(compound.Props.ConvertAll(p => p.Name).ToArray())});");
            }
            foreach (var compound in model.CompoundIndexes)
            {
                EmitCompoundComparer(sb, compound, indent);
            }
            sb.AppendLine($"{indent}    }}");
            sb.AppendLine();
        }

        EmitWriteRow(sb, model, self, indent);
        sb.AppendLine();
        EmitReadRow(sb, model, self, indent);
        sb.AppendLine();

        // Key serializers.
        sb.AppendLine($"{indent}    private static void __BlazeWriteKey({Writer} writer, {keyType} key)");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        {BlazeDbTypeMap.WriteExpr(key.Kind, "writer", "key")};");
        sb.AppendLine($"{indent}    }}");
        sb.AppendLine();
        sb.AppendLine($"{indent}    private static {keyType} __BlazeReadKey(ref {Reader} reader)");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        return {BlazeDbTypeMap.ReadExpr(key.Kind, "reader", key.ScalarTypeDisplay)};");
        sb.AppendLine($"{indent}    }}");

        sb.AppendLine($"{indent}}}");
        if (model.Namespace != null)
        {
            sb.AppendLine("}");
        }
        return sb.ToString();
    }

    /// <summary>
    /// A value tuple compares its members with <c>Comparer&lt;T&gt;.Default</c>, which for a string
    /// means the current culture - so the ordinal default a single-property index gets from
    /// <c>BlazeDbOrderedIndexDefinition</c> cannot reach the members inside a tuple. A compound
    /// ordered index over a string therefore carries a comparer that walks the members itself,
    /// identically to the tuple except for comparing strings ordinally. Nothing else needs one:
    /// hash indexes already compare strings ordinally, through <c>EqualityComparer</c>.
    /// </summary>
    private static bool NeedsCompoundComparer(BlazeDbCompoundIndexModel compound) =>
        compound.Ordered && compound.Props.Exists(p => p.Kind == BlazeDbScalarKind.String);

    private static string CompoundComparer(BlazeDbCompoundIndexModel compound) =>
        NeedsCompoundComparer(compound) ? $"{ComparerName(compound)}.Instance" : "null";

    private static string ComparerName(BlazeDbCompoundIndexModel compound) => "__Blaze" + compound.Name + "Comparer";

    private static void EmitCompoundComparer(StringBuilder sb, BlazeDbCompoundIndexModel compound, string indent)
    {
        if (!NeedsCompoundComparer(compound))
        {
            return;
        }

        var tuple = compound.TupleType;
        var name = ComparerName(compound);
        sb.AppendLine();
        sb.AppendLine($"{indent}        private sealed class {name} : global::System.Collections.Generic.IComparer<{tuple}>");
        sb.AppendLine($"{indent}        {{");
        sb.AppendLine($"{indent}            public static readonly {name} Instance = new();");
        sb.AppendLine();
        sb.AppendLine($"{indent}            public int Compare({tuple} x, {tuple} y)");
        sb.AppendLine($"{indent}            {{");
        sb.AppendLine($"{indent}                int __c;");
        foreach (var prop in compound.Props)
        {
            var compare = prop.Kind == BlazeDbScalarKind.String
                ? $"global::System.StringComparer.Ordinal.Compare(x.{prop.Name}, y.{prop.Name})"
                : $"global::System.Collections.Generic.Comparer<{prop.TypeDisplay}>.Default.Compare(x.{prop.Name}, y.{prop.Name})";
            sb.AppendLine($"{indent}                __c = {compare};");
            sb.AppendLine($"{indent}                if (__c != 0) return __c;");
        }
        sb.AppendLine($"{indent}                return 0;");
        sb.AppendLine($"{indent}            }}");
        sb.AppendLine($"{indent}        }}");
    }

    private static void EmitWriteRow(StringBuilder sb, BlazeDbTableModel model, string self, string indent)
    {
        sb.AppendLine($"{indent}    private static void __BlazeWriteRow({Writer} writer, {self} row)");
        sb.AppendLine($"{indent}    {{");
        foreach (var prop in model.Props)
        {
            var tag = $"writer.WriteTag({prop.FieldNumber}, {BlazeDbTypeMap.WireType(prop.Kind)});";
            switch (prop.Category)
            {
                case BlazeDbPropCategory.Scalar when !BlazeDbTypeMap.IsReferenceScalar(prop.Kind):
                    sb.AppendLine($"{indent}        {tag}");
                    sb.AppendLine($"{indent}        {BlazeDbTypeMap.WriteExpr(prop.Kind, "writer", "row." + prop.Name)};");
                    break;

                case BlazeDbPropCategory.Scalar:
                case BlazeDbPropCategory.NullableRefScalar:
                    sb.AppendLine($"{indent}        if (row.{prop.Name} is not null)");
                    sb.AppendLine($"{indent}        {{");
                    sb.AppendLine($"{indent}            {tag}");
                    sb.AppendLine($"{indent}            {BlazeDbTypeMap.WriteExpr(prop.Kind, "writer", "row." + prop.Name)};");
                    sb.AppendLine($"{indent}        }}");
                    break;

                case BlazeDbPropCategory.NullableValueScalar:
                    sb.AppendLine($"{indent}        if (row.{prop.Name} is not null)");
                    sb.AppendLine($"{indent}        {{");
                    sb.AppendLine($"{indent}            {tag}");
                    sb.AppendLine($"{indent}            {BlazeDbTypeMap.WriteExpr(prop.Kind, "writer", "row." + prop.Name + ".Value")};");
                    sb.AppendLine($"{indent}        }}");
                    break;

                case BlazeDbPropCategory.ListCollection:
                case BlazeDbPropCategory.ArrayCollection:
                    sb.AppendLine($"{indent}        if (row.{prop.Name} is not null)");
                    sb.AppendLine($"{indent}        {{");
                    sb.AppendLine($"{indent}            foreach (var __element in row.{prop.Name})");
                    sb.AppendLine($"{indent}            {{");
                    sb.AppendLine($"{indent}                {tag}");
                    sb.AppendLine($"{indent}                {BlazeDbTypeMap.WriteExpr(prop.Kind, "writer", "__element")};");
                    sb.AppendLine($"{indent}            }}");
                    sb.AppendLine($"{indent}        }}");
                    break;
            }
        }
        sb.AppendLine($"{indent}    }}");
    }

    private static void EmitReadRow(StringBuilder sb, BlazeDbTableModel model, string self, string indent)
    {
        sb.AppendLine($"{indent}    private static {self} __BlazeReadRow(ref {Reader} reader)");
        sb.AppendLine($"{indent}    {{");

        foreach (var prop in model.Props)
        {
            var local = "__v" + prop.FieldNumber;
            switch (prop.Category)
            {
                case BlazeDbPropCategory.Scalar:
                    sb.AppendLine($"{indent}        {prop.TypeDisplay} {local} = {BlazeDbTypeMap.DefaultExpr(prop.Kind, prop.ScalarTypeDisplay)};");
                    break;
                case BlazeDbPropCategory.NullableValueScalar:
                case BlazeDbPropCategory.NullableRefScalar:
                    sb.AppendLine($"{indent}        {prop.TypeDisplay} {local} = default;");
                    break;
                case BlazeDbPropCategory.ListCollection:
                case BlazeDbPropCategory.ArrayCollection:
                    sb.AppendLine($"{indent}        global::System.Collections.Generic.List<{prop.ScalarTypeDisplay}>? {local} = null;");
                    break;
            }
        }

        sb.AppendLine($"{indent}        while (reader.Remaining > 0)");
        sb.AppendLine($"{indent}        {{");
        sb.AppendLine($"{indent}            var (__field, __wire) = reader.ReadTag();");
        sb.AppendLine($"{indent}            switch (__field)");
        sb.AppendLine($"{indent}            {{");
        foreach (var prop in model.Props)
        {
            var local = "__v" + prop.FieldNumber;
            var read = BlazeDbTypeMap.ReadExpr(prop.Kind, "reader", prop.ScalarTypeDisplay);
            // A field number that comes back with a different wire type than this reader expects
            // was written by a schema in which the property had another type. Decoding it would
            // misread the bytes (or worse, desynchronize the stream), so it is skipped like an
            // unknown field and the property keeps its default - the same tolerance protobuf has.
            sb.AppendLine($"{indent}                case {prop.FieldNumber} when __wire == {BlazeDbTypeMap.WireType(prop.Kind)}:");
            switch (prop.Category)
            {
                case BlazeDbPropCategory.ListCollection:
                case BlazeDbPropCategory.ArrayCollection:
                    sb.AppendLine($"{indent}                    ({local} ??= new global::System.Collections.Generic.List<{prop.ScalarTypeDisplay}>()).Add({read});");
                    break;
                default:
                    sb.AppendLine($"{indent}                    {local} = {read};");
                    break;
            }
            sb.AppendLine($"{indent}                    break;");
        }
        sb.AppendLine($"{indent}                default:");
        sb.AppendLine($"{indent}                    reader.SkipField(__wire);");
        sb.AppendLine($"{indent}                    break;");
        sb.AppendLine($"{indent}            }}");
        sb.AppendLine($"{indent}        }}");

        sb.AppendLine($"{indent}        return new {self}");
        sb.AppendLine($"{indent}        {{");
        foreach (var prop in model.Props)
        {
            var local = "__v" + prop.FieldNumber;
            var nullableCollection = prop.TypeDisplay.EndsWith("?");
            var assignment = prop.Category switch
            {
                BlazeDbPropCategory.ListCollection => nullableCollection
                    ? local
                    : $"{local} ?? new global::System.Collections.Generic.List<{prop.ScalarTypeDisplay}>()",
                BlazeDbPropCategory.ArrayCollection => nullableCollection
                    ? $"{local}?.ToArray()"
                    : $"{local} is null ? global::System.Array.Empty<{prop.ScalarTypeDisplay}>() : {local}.ToArray()",
                _ => local,
            };
            sb.AppendLine($"{indent}            {prop.Name} = {assignment},");
        }
        sb.AppendLine($"{indent}        }};");
        sb.AppendLine($"{indent}    }}");
    }
}
