using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace BlazeDb.SourceGen;

internal static class SourceEmitter
{
    private const string Writer = "global::BlazeDb.Serialization.BufferWriter";
    private const string Reader = "global::BlazeDb.Serialization.BufferReader";

    private static string Bool(bool value) => value ? "true" : "false";

    private static string Members(params string[] names) =>
        "new string[] { " + string.Join(", ", Array.ConvertAll(names, n => "\"" + n + "\"")) + " }";

    public static string Emit(TableModel model)
    {
        var self = model.Namespace is null
            ? "global::" + model.TypeName
            : "global::" + model.Namespace + "." + model.TypeName;
        var key = model.Key!;
        var keyType = key.ScalarTypeDisplay;
        var indent = model.Namespace is null ? "" : "    ";

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by BlazeDb.SourceGen />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        if (model.Namespace != null)
        {
            sb.AppendLine($"namespace {model.Namespace}");
            sb.AppendLine("{");
        }

        sb.AppendLine($"{indent}partial {model.TypeKeyword} {model.TypeName}");
        sb.AppendLine($"{indent}{{");

        // Descriptor.
        var indexed = model.Props.Where(p => p.HashIndexName != null || p.OrderedIndexName != null).ToList();
        var indexRefs = new List<string>();
        foreach (var prop in indexed)
        {
            if (prop.HashIndexName != null)
            {
                indexRefs.Add("Indexes." + prop.HashIndexName);
            }
            if (prop.OrderedIndexName != null)
            {
                indexRefs.Add("Indexes." + prop.OrderedIndexName);
            }
        }
        foreach (var compound in model.CompoundIndexes)
        {
            indexRefs.Add("Indexes." + compound.Name);
        }
        var indexArg = indexRefs.Count == 0
            ? "null"
            : $"new global::BlazeDb.IndexDefinition<{self}>[] {{ {string.Join(", ", indexRefs)} }}";

        sb.AppendLine($"{indent}    /// <summary>Generated BlazeDb table descriptor for this type.</summary>");
        sb.AppendLine($"{indent}    public static readonly global::BlazeDb.TableDescriptor<{keyType}, {self}> Table = new(");
        sb.AppendLine($"{indent}        \"{model.TableName}\",");
        sb.AppendLine($"{indent}        static row => row.{key.Name},");
        sb.AppendLine($"{indent}        __BlazeWriteRow,");
        sb.AppendLine($"{indent}        __BlazeReadRow,");
        sb.AppendLine($"{indent}        __BlazeWriteKey,");
        sb.AppendLine($"{indent}        __BlazeReadKey,");
        sb.AppendLine($"{indent}        {indexArg},");
        sb.AppendLine($"{indent}        keyMember: \"{key.Name}\");");
        sb.AppendLine();

        // Index definitions.
        if (indexRefs.Count > 0)
        {
            sb.AppendLine($"{indent}    /// <summary>Generated secondary index definitions.</summary>");
            sb.AppendLine($"{indent}    public static class Indexes");
            sb.AppendLine($"{indent}    {{");
            foreach (var prop in indexed)
            {
                if (prop.HashIndexName != null)
                {
                    sb.AppendLine($"{indent}        public static readonly global::BlazeDb.HashIndexDefinition<{self}, {prop.TypeDisplay}> {prop.HashIndexName} =");
                    sb.AppendLine($"{indent}            new(\"{prop.HashIndexName}\", static row => row.{prop.Name}, null, {Bool(prop.HashIndexUnique)}, {Members(prop.Name)});");
                }
                if (prop.OrderedIndexName != null)
                {
                    sb.AppendLine($"{indent}        public static readonly global::BlazeDb.OrderedIndexDefinition<{self}, {prop.TypeDisplay}> {prop.OrderedIndexName} =");
                    sb.AppendLine($"{indent}            new(\"{prop.OrderedIndexName}\", static row => row.{prop.Name}, null, {Bool(prop.OrderedIndexUnique)}, {Members(prop.Name)});");
                }
            }
            foreach (var compound in model.CompoundIndexes)
            {
                var tuple = compound.TupleType;
                var ctor = "(" + string.Join(", ", compound.Props.ConvertAll(p => "row." + p.Name)) + ")";
                var defType = compound.Ordered ? "OrderedIndexDefinition" : "HashIndexDefinition";
                sb.AppendLine($"{indent}        public static readonly global::BlazeDb.{defType}<{self}, {tuple}> {compound.Name} =");
                sb.AppendLine($"{indent}            new(\"{compound.Name}\", static row => {ctor}, null, {Bool(compound.Unique)}, {Members(compound.Props.ConvertAll(p => p.Name).ToArray())});");
            }
            sb.AppendLine($"{indent}    }}");
            sb.AppendLine();
        }

        EmitWriteRow(sb, model, self, indent);
        sb.AppendLine();
        EmitReadRow(sb, model, self, indent);
        sb.AppendLine();

        // Key serializers.
        sb.AppendLine($"{indent}    private static void __BlazeWriteKey({Writer} writer, {keyType} key)");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        {TypeMap.WriteExpr(key.Kind, "writer", "key")};");
        sb.AppendLine($"{indent}    }}");
        sb.AppendLine();
        sb.AppendLine($"{indent}    private static {keyType} __BlazeReadKey(ref {Reader} reader)");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        return {TypeMap.ReadExpr(key.Kind, "reader", key.ScalarTypeDisplay)};");
        sb.AppendLine($"{indent}    }}");

        sb.AppendLine($"{indent}}}");
        if (model.Namespace != null)
        {
            sb.AppendLine("}");
        }
        return sb.ToString();
    }

    private static void EmitWriteRow(StringBuilder sb, TableModel model, string self, string indent)
    {
        sb.AppendLine($"{indent}    private static void __BlazeWriteRow({Writer} writer, {self} row)");
        sb.AppendLine($"{indent}    {{");
        foreach (var prop in model.Props)
        {
            var tag = $"writer.WriteTag({prop.FieldNumber}, {TypeMap.WireType(prop.Kind)});";
            switch (prop.Category)
            {
                case PropCategory.Scalar when !TypeMap.IsReferenceScalar(prop.Kind):
                    sb.AppendLine($"{indent}        {tag}");
                    sb.AppendLine($"{indent}        {TypeMap.WriteExpr(prop.Kind, "writer", "row." + prop.Name)};");
                    break;

                case PropCategory.Scalar:
                case PropCategory.NullableRefScalar:
                    sb.AppendLine($"{indent}        if (row.{prop.Name} is not null)");
                    sb.AppendLine($"{indent}        {{");
                    sb.AppendLine($"{indent}            {tag}");
                    sb.AppendLine($"{indent}            {TypeMap.WriteExpr(prop.Kind, "writer", "row." + prop.Name)};");
                    sb.AppendLine($"{indent}        }}");
                    break;

                case PropCategory.NullableValueScalar:
                    sb.AppendLine($"{indent}        if (row.{prop.Name} is not null)");
                    sb.AppendLine($"{indent}        {{");
                    sb.AppendLine($"{indent}            {tag}");
                    sb.AppendLine($"{indent}            {TypeMap.WriteExpr(prop.Kind, "writer", "row." + prop.Name + ".Value")};");
                    sb.AppendLine($"{indent}        }}");
                    break;

                case PropCategory.ListCollection:
                case PropCategory.ArrayCollection:
                    sb.AppendLine($"{indent}        if (row.{prop.Name} is not null)");
                    sb.AppendLine($"{indent}        {{");
                    sb.AppendLine($"{indent}            foreach (var __element in row.{prop.Name})");
                    sb.AppendLine($"{indent}            {{");
                    sb.AppendLine($"{indent}                {tag}");
                    sb.AppendLine($"{indent}                {TypeMap.WriteExpr(prop.Kind, "writer", "__element")};");
                    sb.AppendLine($"{indent}            }}");
                    sb.AppendLine($"{indent}        }}");
                    break;
            }
        }
        sb.AppendLine($"{indent}    }}");
    }

    private static void EmitReadRow(StringBuilder sb, TableModel model, string self, string indent)
    {
        sb.AppendLine($"{indent}    private static {self} __BlazeReadRow(ref {Reader} reader)");
        sb.AppendLine($"{indent}    {{");

        foreach (var prop in model.Props)
        {
            var local = "__v" + prop.FieldNumber;
            switch (prop.Category)
            {
                case PropCategory.Scalar:
                    sb.AppendLine($"{indent}        {prop.TypeDisplay} {local} = {TypeMap.DefaultExpr(prop.Kind, prop.ScalarTypeDisplay)};");
                    break;
                case PropCategory.NullableValueScalar:
                case PropCategory.NullableRefScalar:
                    sb.AppendLine($"{indent}        {prop.TypeDisplay} {local} = default;");
                    break;
                case PropCategory.ListCollection:
                case PropCategory.ArrayCollection:
                    sb.AppendLine($"{indent}        global::System.Collections.Generic.List<{prop.ScalarTypeDisplay}>? {local} = null;");
                    break;
            }
        }

        sb.AppendLine($"{indent}        while (reader.Remaining > 0)");
        sb.AppendLine($"{indent}        {{");
        sb.AppendLine($"{indent}            var (__field, __wire) = reader.ReadTag();");
        sb.AppendLine($"{indent}            switch (__field)");
        sb.AppendLine($"{indent}            {{");
        foreach (var prop in model.Props)
        {
            var local = "__v" + prop.FieldNumber;
            var read = TypeMap.ReadExpr(prop.Kind, "reader", prop.ScalarTypeDisplay);
            // A field number that comes back with a different wire type than this reader expects
            // was written by a schema in which the property had another type. Decoding it would
            // misread the bytes (or worse, desynchronize the stream), so it is skipped like an
            // unknown field and the property keeps its default - the same tolerance protobuf has.
            sb.AppendLine($"{indent}                case {prop.FieldNumber} when __wire == {TypeMap.WireType(prop.Kind)}:");
            switch (prop.Category)
            {
                case PropCategory.ListCollection:
                case PropCategory.ArrayCollection:
                    sb.AppendLine($"{indent}                    ({local} ??= new global::System.Collections.Generic.List<{prop.ScalarTypeDisplay}>()).Add({read});");
                    break;
                default:
                    sb.AppendLine($"{indent}                    {local} = {read};");
                    break;
            }
            sb.AppendLine($"{indent}                    break;");
        }
        sb.AppendLine($"{indent}                default:");
        sb.AppendLine($"{indent}                    reader.SkipField(__wire);");
        sb.AppendLine($"{indent}                    break;");
        sb.AppendLine($"{indent}            }}");
        sb.AppendLine($"{indent}        }}");

        sb.AppendLine($"{indent}        return new {self}");
        sb.AppendLine($"{indent}        {{");
        foreach (var prop in model.Props)
        {
            var local = "__v" + prop.FieldNumber;
            var nullableCollection = prop.TypeDisplay.EndsWith("?");
            var assignment = prop.Category switch
            {
                PropCategory.ListCollection => nullableCollection
                    ? local
                    : $"{local} ?? new global::System.Collections.Generic.List<{prop.ScalarTypeDisplay}>()",
                PropCategory.ArrayCollection => nullableCollection
                    ? $"{local}?.ToArray()"
                    : $"{local} is null ? global::System.Array.Empty<{prop.ScalarTypeDisplay}>() : {local}.ToArray()",
                _ => local,
            };
            sb.AppendLine($"{indent}            {prop.Name} = {assignment},");
        }
        sb.AppendLine($"{indent}        }};");
        sb.AppendLine($"{indent}    }}");
    }
}
